### PR TITLE
Expose proc_macro's before() and after() methods on Span

### PR DESCRIPTION
**Pull request by dtolnay**
Tracking issue: https://github.com/rust-lang/rust/issues/87552

### CODE REVIEW

**Comment by huybuidac** [comment]
hey, it causes "unknown feature `proc_macro_span_shrink`", what should I do?

**Comment by BestRamsay** [comment]
@dtolnay, How i can resolve error[E0635]: unknown feature `proc_macro_span_shrink` ??

**Comment by taiki-e** [comment]
@huybuidac @BestRamsay: I think you need to upgrade the nightly toolchain to nightly-2021-10-11 or later, downgrade proc-macro2 to 1.0.43, or use a non-nightly toolchain.

**Comment by adamhfox** [comment]
@taiki-e any other potential solutions seems to cause more errors for me

**Comment by taiki-e** [comment]
@adamhfox: Since none of you provided specific information about the project where the error occurred, I talked about the basic case.
That said, I would be surprised if downgrading proc-macro2 (`cargo update -p proc-macro2 --precise 1.0.43`) does not work.

**Comment by adamhfox** [comment]
> cargo update -p proc-macro2 --precise 1.0.43

Thank you, that solved it

The problem arised for me  when creating a new anchor project

**Pull request merged**
